// import React from 'react';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9X41jnW0Ojm
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from '@/components/ui/button';
import Image from 'next/image';

const Cigarrillo = ({
  marca,
  precio,

  cantidad,
  imagen,
  agregarCigarrillo,
  eliminarCigarrillo,
}) => {
  return (
    <section className="w-full py-12 ">
      <div className="container grid gap-8 px-4 md:px-6">
        <div className="sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          <div className="grid grid-cols-[1fr_2fr] gap-6 bg-white rounded-lg shadow-xl dark:bg-gray-950">
            <div className="rounded-l-lg overflow-hidden">
              <Image
                alt="Product Image"
                className="w-full h-full object-cover"
                height={400}
                src={imagen}
                style={{
                  aspectRatio: '400/400',
                  objectFit: 'cover',
                }}
                width={400}
              />
            </div>
            <div className="p-4 flex flex-col justify-between">
              <div className="grid gap-2">
                <h3 className="font-semibold text-lg">{marca}</h3>
                {/* <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                  Innovative widgets for all your needs. Durable and reliable.
                </p> */}
                <div className="flex flex-col items-center gap-2">
                  <span className="text-2xl font-bold">${precio}</span>

                  {/* <span className="text-sm text-gray-500 dark:text-gray-400 line-through">
                    $24.99
                  </span> */}
                </div>
              </div>
              {/* BOTONES PRECIO X10 */}
              <div className="flex items-center gap-4 mt-4">
                <div className="flex items-center gap-2">
                  <Button
                    onClick={eliminarCigarrillo}
                    className="p-1"
                    size="icon"
                    variant="outline"
                  >
                    <MinusIcon className="w-4 h-4" />
                  </Button>
                  <span className="text-lg font-medium">{cantidad}</span>
                  <Button
                    onClick={agregarCigarrillo}
                    className="p-1"
                    size="icon"
                    variant="outline"
                  >
                    <PlusIcon className="w-4 h-4" />
                  </Button>
                </div>
                {/* <Button className="p-1" size="icon" variant="outline">
                  <TrashIcon className="w-4 h-4" />
                  <span className="sr-only">Remove</span>
                </Button> */}
              </div>
              {/* BOTONES PRECIOS POR 1 */}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Cigarrillo;

function MinusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
    </svg>
  );
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  );
}

// const Cigarrillo = ({
//   marca,
//   precio,
//   cantidad,
//   agregarCigarrillo,
//   eliminarCigarrillo,
// }) => {
//   return (
//     <div>
//       <p>
//         {marca} - ${precio} - Cantidad: {cantidad}
//       </p>
//       <button onClick={agregarCigarrillo}>Agregar</button>
//       <button onClick={eliminarCigarrillo}>Eliminar</button>
//     </div>
//   );
// };

// export default Cigarrillo;
